### ISSUE TITLE
CSS checklist

### ISSUE THREAD

**Issue by Rinsworth** [Rinsworth/fa21-cse110-lab3#2]
- [x] Comments
- [x] rgb color
- [x] hex color
- [x] hsl color
- [x] color name
- [x] background-color
- [x] absolute units (pc, px, pt)
- [x] relative units (em, ex, rem)
- [x] long margin
- [x] short margin
- [x] auto margin
- [x] long padding
- [x] short padding
- [x] border-style
- [x] border-color
- [x] border-width
- [x] border-radius
- [x] text color
- [x] text-decoration
- [x] text-align
- [x] display (none, block inline-block, inline)
- [x] display property
- [x] height
- [x] width
- [x] max-width
- [x] min-width
- [x] position (static, relative, fixed, absolute, sticky)
- [x] pseudo-class hover
- [x] pseudo-class active
- [x] flexbox
- [x] grid
- [x] media query
- [x] fonts

**Comment by Rinsworth** [comment]
Done!
